# -*- coding: utf-8 -*-
"""chatbot_ISDS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smwPBM_ovFqAZ4P5WeXMmW3L01fObqxL

# **Section A - Setup**
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install chromadb voyageai pymupdf pypdf openpyxl anthropic gradio --quiet

import chromadb
import voyageai
import pypdf
import openpyxl
import pymupdf
print("All five libraries imported successfully")

# Import necessary libraries
from google.colab import userdata
import anthropic

# Retrieve your API key from Colab's secrets manager
ANTHROPIC_API_KEY = userdata.get('Anthropickey')

# Initialize the Anthropic client
client = anthropic.Anthropic(api_key= ANTHROPIC_API_KEY)

# Voyage
VOYAGE_API_KEY = userdata.get('voyage_ai')
vo = voyageai.Client(api_key=VOYAGE_API_KEY)

print("Clients ready.")

# === SETUP: connect to the existing corpus (run every session — free) ===

chroma_path = '/content/drive/MyDrive/intl_arb_bot/chroma_db'
COLLECTION_NAME = "isds_corpus_v1"
EXPECTED_CHUNKS = 934

chroma_client = chromadb.PersistentClient(path=chroma_path)
collection = chroma_client.get_or_create_collection(name=COLLECTION_NAME)

n = collection.count()
print(f"Connected to '{COLLECTION_NAME}': {n} chunks on disk")
if n == EXPECTED_CHUNKS:
    print("✓ Corpus ready. Skip Section B entirely.")
elif n == 0:
    print("⚠ Empty — run Section B ONCE to build it.")
else:
    print(f"⚠ Partial ({n}/{EXPECTED_CHUNKS}) — re-run all of Section B to rebuild.")

# ---- Storage cell edit: one added line in the metadata dict ----
# 'search_terms': clean_metadata_value(chunk.get('search_terms', '')),

# ---- New retrieve(): prepends identity to what the RERANKER reads ----
def retrieve(query, n_results=10, n_candidates=100, per_doc_cap=4):
    """
    Two-stage retrieval:
      1. Embedding search over the contextually-tagged index (wide candidate pool).
      2. Voyage cross-encoder reranks those candidates. The reranker reads the
         ORIGINAL chunk text, so we prepend each candidate's identity (search
         terms, title, type, jurisdiction) before scoring — otherwise it cannot
         tell which court a passage comes from.
      3. Return the top n_results, capped per document for diversity.
    Stored text and what the bot sees are unchanged; the identity prefix is used
    for scoring only.
    """
    # --- Stage 1: wide embedding search ---
    query_embedding = vo.embed(
        texts=[query], model="voyage-law-2", input_type="query"
    ).embeddings[0]
    raw = collection.query(
        query_embeddings=[query_embedding],
        n_results=n_candidates,
        include=['documents', 'metadatas', 'distances'],
    )
    candidates = []
    for i in range(len(raw['ids'][0])):
        candidates.append({
            'chunk_id': raw['ids'][0][i],
            'text': raw['documents'][0][i],
            'metadata': raw['metadatas'][0][i],
            'distance': raw['distances'][0][i],
        })

    # --- Build the identity-prefixed text the reranker will score ---
    def rerank_input(c):
        m = c['metadata']
        bits = [m.get('search_terms', ''), m.get('source_title', ''),
                m.get('subfolder', ''), m.get('jurisdiction', '')]
        ident = " | ".join(b for b in bits if b)
        return (ident + "\n\n" + c['text']) if ident else c['text']

    # --- Stage 2: rerank ---
    rr = vo.rerank(
        query=query,
        documents=[rerank_input(c) for c in candidates],
        model="rerank-2.5",
        top_k=len(candidates),
    )

    # --- Stage 3: take top n_results with a per-document cap ---
    final, per_doc = [], {}
    for item in rr.results:
        c = dict(candidates[item.index])
        c['rerank_score'] = item.relevance_score
        doc = c['metadata']['source_file']
        if per_doc.get(doc, 0) >= per_doc_cap:
            continue
        final.append(c)
        per_doc[doc] = per_doc.get(doc, 0) + 1
        if len(final) == n_results:
            break

    return final

SYSTEM_PROMPT = """You are a research assistant for intra-EU and UK investor-state dispute settlement (ISDS), built for junior researchers (LLM/PhD students, paralegals, trainees, junior associates, NQs) producing first-pass research notes, case orientation, and saga tracking.

## How to use the retrieved sources

You will be given a set of source excerpts retrieved from a curated corpus. These are your ONLY substantive knowledge base. Every factual or doctrinal claim in your answer must be grounded in these excerpts.

You may use general legal knowledge from your training ONLY for:
- Defining standard legal terms (e.g., what is an Advocate General, what is FET, what is ICSID)
- Providing context about institutions (e.g., what is the CJEU, what is UNCITRAL)
- Explaining basic legal concepts when needed for clarity

For ANY claim about specific cases, holdings, treaty provisions, doctrinal positions, or what particular sources say, you MUST rely on the retrieved excerpts. Do NOT supplement with case knowledge from training, because that knowledge may be outdated, imprecise, or hallucinated.

## Citation discipline

Every factual or doctrinal claim must be followed by a citation in the form [Source N], referring to the numbered sources provided.

Quotation marks are reserved strictly for a source's exact words. If text appears in quotation marks it must be verbatim — copied from a retrieved chunk, never reconstructed, approximated, or tidied up — and it must carry its [Source N]. Keep quotations short (one or two sentences).

When you put something in your own words, do NOT use quotation marks, and phrase it so it reads as your rendering rather than the source's language (e.g. "In substance, the Court reasoned that…", "Paraphrasing the judgment,…"). A reader must be able to tell at a glance what is the court's exact wording and what is your summary: if it is not in quotation marks, it is not the source's words. Never phrase a paraphrase so that a reader could lift it and quote it as the court's language.

## Pinpoint citations and named sources

If the user asks for a specific locator — a paragraph number, article, or section — from a named source (e.g. "the Supreme Court's paragraph on prior written agreement"), you may give it ONLY if that locator actually appears in the retrieved chunks of that specific source.

Never supply a paragraph, article, or section number that comes from a different source than the one asked about — attaching a real-looking citation to the wrong source is a serious error.

If you cannot find the locator in the named source's retrieved chunks, do not say it does not exist, and do not imply the corpus is incomplete or that anything "was not retrieved." Say only that you could not find the specific paragraph among the sources available to you — e.g. "I couldn't locate the specific paragraph for this point in the Supreme Court judgment among the sources available to me. I can give you the substance of the point from what I have, and you can confirm the exact paragraph in the full judgment." Offer the substance if you have it, and never guess a number.

## Distinguishing source content from inference

Structure your answers to make epistemic status visible. Use these distinctions:

- "What the sources say": direct content from the retrieved excerpts, with citations
- "Reading these together" or "Taking these sources together": synthesis across multiple sources, with citations to each
- "Inference": claims that go beyond what the sources directly state, clearly labelled as your reasoning rather than the sources' words

Never blur these. If you are inferring, say so explicitly.

## Calibrated linguistic register

Match your language to your actual confidence and to the type of support:

- Verbatim quotation (in quotation marks, exact): state it directly. The Court held that "…" [Source N]
- Your paraphrase of a single source: no quotation marks, lightly hedged and marked as your rendering. "In substance, the Court reasoned that…" [Source N]
- Synthesis across sources: more hedged. "Reading these together, the position appears to be…" [Source N][Source M]
- Inference beyond what the sources state: strongly hedged and labelled. "Based on these sources, one possible reading is…"
- No support found among the sources: do not answer from training data (see below).

Do not produce uniformly confident prose, and never let a paraphrase borrow the authority of a quotation.

Two rules on confidence, both important:

**Never strengthen a source's hedge.** If a source is tentative, your restatement must be equally tentative. If commentary says an outcome is "likely" or a chapter is "likely to be closed," do not report it as settled, final, or certain. Carry the source's own level of confidence through into your answer.

**Label evaluative conclusions as inference.** If you reach a judgement the sources do not themselves state — that a body was "correct," that an analysis was "sound," that two positions are reconcilable — that is your reasoning, not a finding in the sources. Say so explicitly ("Reading these together, one reading is…") and hedge it. Never state an evaluative conclusion in the same confident register you use for a sourced holding.

## When you can't find support in the sources

If you cannot find material relevant to the question among the sources available to you, say so plainly and do not fall back on training data. Frame it as your own inability to find supporting material — never as a statement about what the corpus contains or whether something exists, which you have no way of knowing. Acceptable language: "I couldn't find material on this among the sources available to me, so I can't give you a grounded answer."

If only part of the question is supported, answer that part and say, in the same terms, that you couldn't find support for the rest.

## You cannot give legal advice or predict outcomes

You cannot reliably give legal advice — not as a matter of policy, but in fact. Advice means applying law to a person's specific, verified facts and exercising professional judgment; you work from a limited set of retrieved excerpts, cannot verify anyone's facts, and cannot weigh the specifics that decide outcomes. Anything resembling advice or a prediction would be unreliable by construction. For the same reason you cannot:
- apply doctrine to a user's facts to assess the merits of their situation
- predict the outcome of a pending, hypothetical, or specific dispute
- recommend a strategy, forum, or type of filing

What you can do:
- describe how cases in the corpus have approached similar issues
- explain the doctrinal framework relevant to a situation
- direct the user to qualified legal counsel for application to their facts

When a user asks for advice or a prediction, say plainly that you can't give it reliably, explain very briefly why, and offer the doctrinal context instead.

## Currency, recency, and the limits of the corpus

Your corpus is a curated set of documents, not a complete or continuously updated record of the law, and it has a cutoff. When a question asks what is most recent, whether a matter has ended or is still ongoing, or whether a position still holds ("is this still the case", "what's the latest", "did the saga end"), you must say plainly that your answer reflects only the documents available to you up to your cutoff, and that developments after that — or matters simply not covered by the corpus — would not be visible to you.

Absence of something in your sources is not evidence that it did not happen. Never present the most recent document you happen to have as "the final position" or "the end of the matter" unless a source expressly says so — and even then, carry the source's own hedging (see the calibration rules above).

## When a question contains a false premise

If a question assumes something the sources contradict — that a court agreed when it in fact disagreed, that a case was decided a certain way when it was not — correct the premise directly and early, then answer what the sources actually support. Do not soften this into an inability to find material: if the sources show the opposite, say so plainly ("The Court of Appeal did not agree with Dias J — it rejected that reasoning at [para]…"), rather than only reporting that you could not locate the passage the question assumed existed.

## Confidentiality and privilege

If a user's question contains case-specific factual details suggestive of a confidential or live matter, caution them once at the start of your response: queries to this tool are transmitted to a third-party API (Anthropic), and entering confidential or privileged material into AI tools may risk waiving legal professional privilege. This is an unsettled and evolving area, so it should be treated cautiously. Then continue with the doctrinal portion of your answer if appropriate.

## Routing notes (internal only)

Some sources have an editorial "routing note," supplied separately under INTERNAL ROUTING GUIDANCE in the user message. These notes are guidance about how to weigh and interpret the sources — e.g., "this is German court commentary, not the CJEU's reasoning" or "this opinion was not followed by the Court." You can refer to these notes to understand connections between documents and context but do not solely rely on them to provide the user information as routing notes are not a primary authority.

You must NEVER quote, cite, paraphrase, or attribute a routing note as if it were source content. They are not evidence and not part of the corpus. Never write "the routing note says...", never cite them as [Source N], and never reveal their existence to the user. If a fact appears ONLY in a routing note and not in the retrieved source text, treat it as unsupported by the sources — do not state it as established.

## Tone and format

Plain, precise prose. No emojis. No marketing language. Headings only when genuinely needed for a multi-part answer. Bullet points when listing multiple distinct items, but prefer prose for analytical content.

Match the length of your answer to the question. A single-fact question ("what was the value of the award?") deserves a sentence or two, not an essay — do not pad a short answer with context the user did not ask for. Reserve long, structured answers for genuinely multi-issue or comparative questions. Being exhaustive is not the same as being useful, and volume can obscure the answer the user actually needs.

Where an answer does run long, end it with a short "In summary" — three or four sentences capturing the key points, so a reader can take the substance without re-reading the whole response.

Do not editorialise about the corpus or about document dates — do not speculate that this is a "test corpus" and do not flag a source's date as being "in the future." Treat the dated sources as authoritative as given.

Do not end every answer with a verification disclaimer — a reflexive footer becomes noise and reads as condescending to a professional reader. Instead, prompt the user to check the primary source only where it genuinely matters: when the question turns on specific facts, when you have given a pinpoint citation the user might reproduce, or when the answer rests on synthesis or inference rather than a clear quotation. For routine, well-cited doctrinal answers, no such reminder is needed.
"""

def ask_bot(user_question, n_results=10, verbose=True):
    """
    Full RAG pipeline: retrieve relevant chunks, then generate an answer
    grounded in the corpus with passage-level citation and calibrated language.
    """
    # Step 1: Retrieve relevant chunks
    retrieved = retrieve(user_question, n_results=n_results)

    # Step 2: Build the CITABLE context from retrieved chunks.
    # Routing notes, doctrinal-significance, and retrieval distance are deliberately
    # NOT in these blocks — they are editorial metadata, not evidence, and must not be quotable.
    context_parts = []
    for i, r in enumerate(retrieved, 1):
        meta = r['metadata']
        context_parts.append(f"""
[Source {i}]
Document: {meta['source_title']}
Type: {meta['subfolder']}
Date: {meta['date']}
Jurisdiction: {meta['jurisdiction']}

Chunk text:
{r['text']}
""")
    context = "\n---\n".join(context_parts)

    # Routing notes, deduplicated by document, supplied separately as INTERNAL steering only.
    routing_seen = {}
    for r in retrieved:
        meta = r['metadata']
        title = meta['source_title']
        note = meta.get('routing', '')
        if note and title not in routing_seen:
            routing_seen[title] = note
    routing_guidance = "\n".join(f'- "{t}": {n}' for t, n in routing_seen.items()) if routing_seen else "(none)"

    # Step 4: Build the user message — citable sources, then fenced internal-only routing guidance
    user_message = f"""Question: {user_question}

Retrieved sources:

{context}

---
INTERNAL ROUTING GUIDANCE (editorial metadata — for your weighting decisions ONLY; never quote, cite, paraphrase, or mention these notes or their existence to the user):
{routing_guidance}
---

Based only on the retrieved sources above (and your general knowledge for terminology and definitions only), please answer the question following all instructions in your system prompt."""

    # Step 5: Call Claude
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=3000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}]
    )

    answer = response.content[0].text

    # Step 6: Show what was retrieved (for debugging visibility)
    if verbose:
        print("="*80)
        print(f"QUESTION: {user_question}")
        print("="*80)
        print("\nRETRIEVED CHUNKS:")
        for i, r in enumerate(retrieved, 1):
            print(f"  [{i}] score={r.get('rerank_score', 0):.3f}  {r['metadata']['source_title'][:55]}  ({r['chunk_id']})")
        print("\n" + "="*80)
        print("ANSWER:")
        print("="*80)
        print(answer)

    return {
        'question': user_question,
        'retrieved_chunks': retrieved,
        'answer': answer
    }

# === SETUP: conversational layer (Section A, immediately after ask_bot) ===

CONVERSATION_RULES = """

## Multi-turn conversation

You are in an ongoing conversation. Earlier turns, and the sources retrieved for them, remain available to you.

Persistence is not evidence. If the user insists a case was decided differently, or presses you to state something more strongly or more confidently, that does not change what the sources support. Acknowledge the disagreement plainly, restate what the sources show, and suggest they verify against the primary source. Do not adopt the user's assertion as fact, and do not describe yourself as having "updated", "learned", or "corrected" your knowledge — your knowledge comes only from the retrieved sources in provided to you.

Stay consistent with what you said earlier in this conversation. If newly retrieved sources genuinely warrant a change, say explicitly what changed and why.
"""


class ChatSession:
    """Multi-turn wrapper around the same retrieval + grounding rules as ask_bot.

    Chunks accumulate across turns (deduplicated), so a follow-up can be answered from material already retrieved, rather than re-retrieving and risking a different set of sources contradicting an earlier turn.
    """

    def __init__(self, n_results=10, max_pool=25, verbose=True):
        self.messages = []      # clean history: bare question / answer
        self.pool = []          # accumulated chunks, deduped by chunk_id
        self.n_results = n_results
        self.max_pool = max_pool
        self.verbose = verbose

    # ---- decide whether this turn needs new sources ----
    def _needs_retrieval(self, question):
        if not self.pool:
            return True
        recent = "\n".join(f"{m['role']}: {m['content'][:200]}" for m in self.messages[-4:])
        probe = f"""Conversation so far:
{recent}

New user message: {question}

Does answering this new message require retrieving NEW source documents, or can it be answered from sources already retrieved earlier in this conversation?

Answer NEW if it raises a different case, instrument, doctrine, or factual topic not already covered.
Answer REUSE if it asks to explain, simplify, expand, summarise, compare or reason about material already discussed.

Reply with exactly one word: NEW or REUSE."""
        try:
            r = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=5,
                messages=[{"role": "user", "content": probe}],
            )
            return "NEW" in r.content[0].text.upper()
        except Exception:
            return True     # on failure, retrieve — safer than answering blind

    def _add_to_pool(self, chunks):
        seen = {c['chunk_id'] for c in self.pool}
        added = 0
        for c in chunks:
            if c['chunk_id'] not in seen:
                self.pool.append(c)
                seen.add(c['chunk_id'])
                added += 1
        if len(self.pool) > self.max_pool:      # keep the most recent
            self.pool = self.pool[-self.max_pool:]
        return added

    def ask(self, question, force_retrieve=None):
        """force_retrieve=None -> decide automatically; True/False -> override."""
        do_retrieve = self._needs_retrieval(question) if force_retrieve is None else force_retrieve

        new_chunks = []
        if do_retrieve:
            new_chunks = retrieve(question, n_results=self.n_results)
            self._add_to_pool(new_chunks)

        # --- build citable context from the WHOLE pool ---
        context_parts = []
        for i, r in enumerate(self.pool, 1):
            meta = r['metadata']
            context_parts.append(f"""
[Source {i}]
Document: {meta['source_title']}
Type: {meta['subfolder']}
Date: {meta['date']}
Jurisdiction: {meta['jurisdiction']}

Chunk text:
{r['text']}
""")
        context = "\n---\n".join(context_parts)

        routing_seen = {}
        for r in self.pool:
            m = r['metadata']
            t, n = m['source_title'], m.get('routing', '')
            if n and t not in routing_seen:
                routing_seen[t] = n
        routing_guidance = "\n".join(f'- "{t}": {n}' for t, n in routing_seen.items()) or "(none)"

        turn_message = f"""Question: {question}

Retrieved sources:

{context}

---
INTERNAL ROUTING GUIDANCE (editorial metadata — for your weighting decisions ONLY; never quote, cite, paraphrase, or mention these notes or their existence to the user):
{routing_guidance}
---

Based only on the retrieved sources above (and your general knowledge for terminology and definitions only), please answer the question following all instructions in your system prompt."""

        # prior turns stay CLEAN; only this turn carries the context payload
        api_messages = list(self.messages) + [{"role": "user", "content": turn_message}]

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=3000,
            system=SYSTEM_PROMPT + CONVERSATION_RULES,
            messages=api_messages,
        )
        answer = response.content[0].text

        self.messages.append({"role": "user", "content": question})   # store bare question
        self.messages.append({"role": "assistant", "content": answer})

        if self.verbose:
            turn_no = sum(1 for m in self.messages if m['role'] == 'user')
            mode = "RETRIEVED new sources" if do_retrieve else "REUSED existing pool"
            print("=" * 80)
            print(f"TURN {turn_no}  |  {mode}  |  pool: {len(self.pool)} chunks")
            print("=" * 80)
            for c in new_chunks:
                print(f"  + {c['metadata']['source_title'][:45]}  ({c['chunk_id']})")
            print("\n" + answer)

        return answer

    def reset(self):
        self.messages, self.pool = [], []
        print("Session reset — history and chunk pool cleared.")

# === SETUP: Chat UI (run LAST in Section A, after ChatSession is defined) ===
# Uses the modern gradio "messages" format: history is a list of
# {"role": "user"/"assistant", "content": "..."} dicts.

import gradio as gr

def build_ui():
    session = {"chat": ChatSession(verbose=False)}   # one live session, resettable

    def respond(message, history):
        if not message.strip():
            return "", history, sources_text(session["chat"])
        try:
            answer = session["chat"].ask(message)
        except Exception as e:
            answer = f"Something went wrong answering that: {e}"
        history = history + [
            {"role": "user", "content": message},
            {"role": "assistant", "content": answer},
        ]
        return "", history, sources_text(session["chat"])

    def sources_text(chat):
        seen, lines = set(), []
        for c in chat.pool:
            t = c["metadata"].get("source_title", "")
            if t and t not in seen:
                seen.add(t); lines.append(f"• {t}")
        return "**Sources in this conversation:**\n" + ("\n".join(lines) if lines else "_(none yet)_")

    def reset():
        session["chat"] = ChatSession(verbose=False)
        return [], "**Sources in this conversation:**\n_(none yet)_"

    with gr.Blocks(title="ISDS Research Assistant") as demo:
        gr.Markdown(
            "# ISDS Research Assistant\n"
            "Answers **only** from a curated corpus of intra-EU / UK investor-state "
            "dispute settlement sources, with citations. It quotes when quoting, hedges "
            "when inferring, and refuses when the sources don't support an answer.\n\n"
            "_Prototype — verify all outputs against primary sources before relying on them._"
        )
        chatbot = gr.Chatbot(height=460)   # <-- modern message format
        with gr.Row():
            box = gr.Textbox(placeholder="Ask about a case, treaty provision, or doctrine…",
                             scale=8, show_label=False)
            send = gr.Button("Send", variant="primary", scale=1)
        clear = gr.Button("New conversation", size="sm")
        sources_md = gr.Markdown("**Sources in this conversation:**\n_(none yet)_")

        box.submit(respond, [box, chatbot], [box, chatbot, sources_md])
        send.click(respond, [box, chatbot], [box, chatbot, sources_md])
        clear.click(reset, None, [chatbot, sources_md])

    return demo

demo = build_ui()
demo.launch(share=True)

"""# Section B - BUILD"""

import os
corpus_path = '/content/drive/MyDrive/intl_arb_bot/corpus_26'
print(os.listdir(corpus_path))

import os

base = '/content/drive/MyDrive/intl_arb_bot/corpus_26'

for folder in ['Case decisions', 'Convention Docs', 'Scholarly Commentary']:
    folder_path = os.path.join(base, folder)
    print(f'\n--- {folder} ---')
    if os.path.exists(folder_path):
        for f in sorted(os.listdir(folder_path)):
            print(f'  {f}')
    else:
        print(f'  FOLDER NOT FOUND at {folder_path}')

import openpyxl

metadata_path = '/content/drive/MyDrive/intl_arb_bot/corpus_26/bot_metadata.xlsx'
wb = openpyxl.load_workbook(metadata_path)
ws = wb.active

# Print first few rows to confirm we can read it
print(f"Sheet name: {ws.title}")
print(f"Total rows: {ws.max_row}")
print(f"\nFirst data row (row 2):")
for cell in ws[2]:
    val = str(cell.value)[:60] if cell.value else "(empty)"
    print(f"  {cell.column_letter}: {val}")

import openpyxl

metadata_path = '/content/drive/MyDrive/intl_arb_bot/corpus_26/bot_metadata.xlsx'
wb = openpyxl.load_workbook(metadata_path)
ws = wb.active
# --- add this just after you open the workbook / before the doc loop ---
header = [c.value for c in ws[1]]
def _find_col(*names):
    for i, h in enumerate(header):
        if h and str(h).strip().lower() in [n.lower() for n in names]:
            return i
    for i, h in enumerate(header):
        if h and 'search' in str(h).lower():
            return i
    return None
ST_IDX = _find_col('search_terms', 'search terms')
print("search_terms column index:", ST_IDX, "->", header[ST_IDX] if ST_IDX is not None else "NOT FOUND")
# Build a list of dictionaries — one per document
documents = []
for row in ws.iter_rows(min_row=2, values_only=True):
    if not row[1]:  # Skip empty rows (no filename in column B)
        continue

    doc = {

        'file_no': row[0],
        'filename': row[1],
        'title': row[2],
        'subfolder': row[3],
        'file_type': row[4],
        'date': row[5],
        'jurisdiction': row[6],
        'key_issues': row[7],
        'summary': row[8],
        'doctrinal_significance': row[9],
        'routing': row[10],
        'search_terms': (row[ST_IDX] if ST_IDX is not None else ''),
    }
    documents.append(doc)

print(f"Loaded {len(documents)} documents from metadata")
print(f"\nFirst document:")
for k, v in documents[0].items():
    val = str(v)[:80] if v else "(empty)"
    print(f"  {k}: {val}")

import os

corpus_base = '/content/drive/MyDrive/intl_arb_bot/corpus_26'

missing = []
found = []
for doc in documents:
    full_path = os.path.join(corpus_base, doc['subfolder'], doc['filename'])
    if os.path.exists(full_path):
        found.append(doc['filename'])
    else:
        missing.append((doc['filename'], full_path))

print(f"Found: {len(found)} files")
print(f"Missing: {len(missing)} files\n")

if missing:
    print("MISSING FILES (script can't find these on disk):")
    for fn, path in missing:
        print(f"  - {fn}")
        print(f"    looked at: {path}")
else:
    print("All files in spreadsheet exist on disk. Ready to extract text.")

try:
   print(f"documents EXISTS:{len(documents)} items, first = {documents[0]['filename']}")
except NameError:
   print("documents NOT DEFINED - the metadata cell hasn't run in this session")
except IndexError:
   print ("documents exists but is EMPTY - the row loop skipped everything")

import os
import fitz  # PyMuPDF

def extract_pdf_text(path):
    """Extract text from a PDF file using PyMuPDF (fitz)."""
    doc = fitz.open(path)
    text_parts = []
    for page in doc:
        text_parts.append(page.get_text())
    doc.close()
    return "\n".join(text_parts)

def extract_txt_text(path):
    """Read text from a .txt file."""
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

# Process every document
extracted = []
failed = []

for doc in documents:
    full_path = os.path.join(corpus_base, doc['subfolder'], doc['filename'])

    try:
        if doc['filename'].lower().endswith('.pdf'):
            text = extract_pdf_text(full_path)
        elif doc['filename'].lower().endswith('.txt'):
            text = extract_txt_text(full_path)
        else:
            failed.append((doc['filename'], 'Unknown file type'))
            continue

        doc_with_text = dict(doc)
        doc_with_text['text'] = text
        doc_with_text['char_count'] = len(text)
        extracted.append(doc_with_text)

    except Exception as e:
        failed.append((doc['filename'], str(e)))

print(f"Successfully extracted: {len(extracted)} documents")
print(f"Failed: {len(failed)} documents\n")

if failed:
    print("FAILURES:")
    for fn, err in failed:
        print(f"  - {fn}: {err}")
else:
    print("✓ All documents extracted.")

print("\nCharacter counts per document:")
for d in extracted:
    print(f"  {d['filename'][:45]:45} {d['char_count']:>10,} chars")

import re

def check_extraction_quality(text, filename):
    """Return a list of warnings about possible extraction issues."""
    warnings = []

    # 1. Suspiciously short
    if len(text) < 1000:
        warnings.append(f"Very short text ({len(text)} chars)")

    # 2. Real broken-word check: look for patterns where a CAPITALIZED short fragment
    # is followed by a lowercase continuation that's not a real word on its own.
    # "Net herlands" matches; "The court" doesn't (both are real words).
    # We look for: capital letter + 2-4 lowercase + space + 4+ lowercase letters,
    # where the second part doesn't start a sentence.
    suspicious = re.findall(r'(?<=[a-z]) ([A-Z][a-z]{1,3}) ([a-z]{4,})', text)
    # Count only those where neither part is a common short word
    common_short = {'The', 'And', 'For', 'But', 'Not', 'All', 'Any', 'One', 'Two',
                    'New', 'Old', 'Mr', 'Ms', 'Dr', 'Lord', 'See'}
    real_suspicious = [s for s in suspicious if s[0] not in common_short]
    if len(real_suspicious) > 50:
        warnings.append(f"Possible broken capitalised words ({len(real_suspicious)} suspicious patterns)")

    # 3. Garbage character ratio
    alpha_chars = sum(1 for c in text if c.isalnum() or c.isspace() or c in '.,;:()-"\'/')
    if alpha_chars / max(len(text), 1) < 0.85:
        warnings.append(f"High proportion of non-text characters")

    # 4. Common English words missing
    common_words = ['the', 'and', 'of', 'to', 'in']
    found_common = sum(1 for w in common_words if f' {w} ' in text.lower())
    if found_common < 3:
        warnings.append(f"Few common English words detected")

    return warnings

print("Quality check results (revised):\n")
flagged = []
clean = []

for d in extracted:
    warnings = check_extraction_quality(d['text'], d['filename'])
    if warnings:
        flagged.append((d['filename'], warnings))
    else:
        clean.append(d['filename'])

print(f"Clean: {len(clean)} documents")
print(f"Flagged for review: {len(flagged)} documents\n")

if flagged:
    print("DOCUMENTS WITH POSSIBLE ISSUES:")
    for fn, warns in flagged:
        print(f"\n  {fn}")
        for w in warns:
            print(f"    ⚠ {w}")
else:
    print("✓ All extractions passed quality checks.")

def chunk_text(text, chunk_size=600, overlap=100):
    """
    Split text into overlapping chunks.

    chunk_size: target number of words per chunk
    overlap: number of words to overlap between consecutive chunks

    Returns a list of chunk strings.
    """
    words = text.split()

    if len(words) <= chunk_size:
        # Document is shorter than one chunk — return as single chunk
        return [text]

    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunk_words = words[start:end]
        chunk_text = ' '.join(chunk_words)
        chunks.append(chunk_text)

        # Move start forward by (chunk_size - overlap) so the next chunk overlaps
        start += chunk_size - overlap

        # If we're near the end, break out so we don't create a tiny final chunk
        if end >= len(words):
            break

    return chunks


# Process every extracted document into chunks
all_chunks = []

for d in extracted:
    doc_chunks = chunk_text(d['text'], chunk_size=600, overlap=100)

    for i, chunk in enumerate(doc_chunks):
        chunk_entry = {
            # Identity
            'chunk_id': f"{d['file_no']}_{i}",  # e.g. "1.0_0", "1.0_1"
            'chunk_index': i,
            'total_chunks_in_doc': len(doc_chunks),
            'text': chunk,
            'word_count': len(chunk.split()),

            # Metadata inherited from the document
            'source_file': d['filename'],
            'source_title': d['title'],
            'subfolder': d['subfolder'],
            'date': d['date'],
            'jurisdiction': d['jurisdiction'],
            'key_issues': d['key_issues'],
            'summary': d['summary'],
            'doctrinal_significance': d['doctrinal_significance'],
            'routing': d['routing'],
            'search_terms': d['search_terms']
        }
        all_chunks.append(chunk_entry)

print(f"Total chunks created: {len(all_chunks)}\n")

# Show distribution: how many chunks per document
print("Chunks per document:")
from collections import Counter
chunk_counts = Counter(c['source_file'] for c in all_chunks)
for fn, count in sorted(chunk_counts.items(), key=lambda x: -x[1]):
    print(f"  {fn[:45]:45} {count:>5} chunks")

print(f"\nSample chunk (first chunk of first doc):")
print(f"  chunk_id: {all_chunks[0]['chunk_id']}")
print(f"  source: {all_chunks[0]['source_file']}")
print(f"  word_count: {all_chunks[0]['word_count']}")
print(f"  text preview: {all_chunks[0]['text'][:300]}...")

import time
import re

# --- Contextual tagging helpers -------------------------------------------
# We embed a TAGGED version of each chunk (identity + locators + text) but
# store the ORIGINAL text, so retrieval gains signal while the bot never
# sees (and so can never quote) the tag.

def extract_locators(text):
    """Locators genuinely present in this chunk.

    Real judgment paragraph numbers ascend through the chunk in document order and
    sit close together. We keep only the longest ascending run with small gaps,
    which rejects footnote markers, article numbers and stray numerals.
    """
    locs = []

    # candidate paragraph markers, IN ORDER OF APPEARANCE
    cands = [int(m.group(1)) for m in
             re.finditer(r'(?:(?<=^)|(?<=\s))\[?(\d{1,3})\]?\s+(?=[A-Z])', text)
             if 1 <= int(m.group(1)) <= 400]

    # longest ascending run with gaps <= 3
    best, cur = [], []
    for n in cands:
        if cur and 0 < n - cur[-1] <= 3:
            cur.append(n)
        else:
            if len(cur) > len(best): best = cur
            cur = [n]
    if len(cur) > len(best): best = cur

    if len(best) >= 2:                       # need a real run, not one stray number
        lo, hi = best[0], best[-1]
        locs.append(f"paragraphs {lo}-{hi}" if lo != hi else f"paragraph {lo}")

    arts = re.findall(r'Article\s+(\d{1,3}(?:\(\d+\))?)', text)
    if arts:
        locs.append("Articles " + ", ".join(list(dict.fromkeys(arts))[:6]))

    return "; ".join(locs)

def build_tagged_text(c):
    """Prepend a short identity/locator tag to the chunk text, for embedding only."""
    parts = []
    if c.get('search_terms'): parts.append(str(c['search_terms']).strip())
    parts.append(str(c.get('source_title', '')).strip())
    if c.get('subfolder'):    parts.append(str(c['subfolder']).strip())
    if c.get('jurisdiction'): parts.append(str(c['jurisdiction']).strip())
    if c.get('date'):         parts.append(str(c['date'])[:10])
    loc = extract_locators(c['text'])
    if loc: parts.append(loc)
    tag = " | ".join(p for p in parts if p)
    return tag + "\n\n" + c['text']

# --- Preview before spending anything --------------------------------------
print("SAMPLE TAGS (check these look right before embedding):")
for i in [0, len(all_chunks)//2, len(all_chunks)-1]:
    print(f"\n--- chunk {all_chunks[i]['chunk_id']} ---")
    print(build_tagged_text(all_chunks[i])[:300])
print("\n" + "="*70 + "\n")

# --- Embedding --------------------------------------------------------------
# Voyage charges per token and has rate limits, so we batch requests
# voyage-law-2 accepts up to 128 chunks per call
BATCH_SIZE = 50

print(f"Embedding {len(all_chunks)} chunks using voyage-law-2...\n")

embedded_chunks = []
failed_chunks = []

# Process in batches
for batch_start in range(0, len(all_chunks), BATCH_SIZE):
    batch_end = min(batch_start + BATCH_SIZE, len(all_chunks))
    batch = all_chunks[batch_start:batch_end]
    batch_texts = [build_tagged_text(c) for c in batch]   # embed the TAGGED text

    try:
        result = vo.embed(
            texts=batch_texts,
            model="voyage-law-2",
            input_type="document"  # tells Voyage these are documents to be indexed
        )

        # Attach each embedding to its corresponding chunk
        # NOTE: dict(chunk) keeps the ORIGINAL 'text' — only the embedding changes
        for chunk, embedding in zip(batch, result.embeddings):
            chunk_with_embedding = dict(chunk)
            chunk_with_embedding['embedding'] = embedding
            embedded_chunks.append(chunk_with_embedding)

        print(f"  Batch {batch_start//BATCH_SIZE + 1}: embedded chunks {batch_start}-{batch_end-1} ({len(batch)} chunks)")

        # Small pause between batches to be polite to the API
        time.sleep(0.5)

    except Exception as e:
        print(f"  Batch {batch_start//BATCH_SIZE + 1} FAILED: {e}")
        for c in batch:
            failed_chunks.append((c['chunk_id'], str(e)))

print(f"\nSuccessfully embedded: {len(embedded_chunks)} chunks")
print(f"Failed: {len(failed_chunks)} chunks")

if failed_chunks:
    print("\nFAILURES:")
    for cid, err in failed_chunks[:5]:
        print(f"  {cid}: {err}")

# Quick check: print the dimensions of the first embedding
if embedded_chunks:
    first_emb = embedded_chunks[0]['embedding']
    print(f"\nEmbedding dimensions: {len(first_emb)}")
    print(f"First 5 values: {first_emb[:5]}")

# === BUILD: store embeddings (guarded; set FORCE_REBUILD=True for a deliberate re-embed) ===
FORCE_REBUILD = False    # <-- True for this tagged re-embed. Set back to False afterwards.

if (not FORCE_REBUILD) and collection.count() == EXPECTED_CHUNKS:
    print(f"Already built ({collection.count()} chunks). Nothing to do.")
else:
    print(f"Building (current: {collection.count()}, FORCE_REBUILD={FORCE_REBUILD})...")
    try:
        chroma_client.delete_collection(COLLECTION_NAME)   # clear old/partial state
    except Exception:
        pass
    collection = chroma_client.create_collection(
        name=COLLECTION_NAME,
        metadata={"description": "Intra-EU and UK ISDS corpus, v1, 25 docs, contextually tagged"},
    )

    def clean_metadata_value(v):
        if v is None: return ""
        if isinstance(v, (str, int, float, bool)): return v
        return str(v)

    ids, embeddings, documents, metadatas = [], [], [], []
    for chunk in embedded_chunks:
        ids.append(chunk['chunk_id'])
        embeddings.append(chunk['embedding'])
        documents.append(chunk['text'])          # ORIGINAL text, not the tagged version
        metadatas.append({
            'source_file': clean_metadata_value(chunk['source_file']),
            'source_title': clean_metadata_value(chunk['source_title']),
            'subfolder': clean_metadata_value(chunk['subfolder']),
            'date': clean_metadata_value(chunk['date']),
            'jurisdiction': clean_metadata_value(chunk['jurisdiction']),
            'key_issues': clean_metadata_value(chunk['key_issues']),
            'summary': clean_metadata_value(chunk['summary']),
            'doctrinal_significance': clean_metadata_value(chunk['doctrinal_significance']),
            'routing': clean_metadata_value(chunk['routing']),
            'search_terms': clean_metadata_value(chunk.get('search_terms', '')),
            'chunk_index': chunk['chunk_index'],
            'total_chunks_in_doc': chunk['total_chunks_in_doc'],
            'word_count': chunk['word_count'],
        })

    BATCH = 100
    for i in range(0, len(ids), BATCH):
        collection.add(
            ids=ids[i:i+BATCH], embeddings=embeddings[i:i+BATCH],
            documents=documents[i:i+BATCH], metadatas=metadatas[i:i+BATCH],
        )
    print(f"✓ Stored {collection.count()} chunks at {chroma_path}")
    print("  Reminder: set FORCE_REBUILD = False now that the rebuild is done.")

"""# Section C - End User POV"""

# _ = ask_bot("What did the Uk Supreme Court hold in ISl v Spain regaridng prior written agreement? give me the paragraph too")

#  #=== USE: eval driver (run when scoring the bot; costs Anthropic per question) ===
# #  results = []

#  def run_eval_question(question, expected_behaviour_note=""):
#      """Run one question through the bot ONCE and capture everything for analysis."""
#      out = ask_bot(question, n_results=10, verbose=True)   # call once
#      results.append({
#          'question': question,
#          'expected': expected_behaviour_note,
#          'retrieved': [
#              (r['chunk_id'], r['metadata']['source_title'][:60], r['distance'])
#              for r in out['retrieved_chunks']
#          ],
#          'answer': out['answer'],
#      })
#      return results[-1]

# import gspread
# from google.auth import default
# from google.colab import auth

# auth.authenticate_user()
# creds, _ = default()
# gc = gspread.authorize(creds)

# EVAL_SHEET_NAME = "v1_eval_queries"    # the Sheet's name as it appears in Drive
# ws = gc.open(EVAL_SHEET_NAME).sheet1             # first tab; use .worksheet("TabName") for another

# rows = ws.get_all_records()                      # list of dicts, keyed by the header row
# print(f"Loaded {len(rows)} rows. Columns found: {list(rows[0].keys())}")

# # Match these two to your sheet's real headers (check the 'Columns found' print above):
# QUESTION_COL = "Question"
# EXPECTED_S = "Expected Sources"
# EXPECTED_A = "Expected Answer"

# eval_set = [(r[QUESTION_COL], r[EXPECTED_S], r[EXPECTED_A]) for r in rows if str(r.get(QUESTION_COL, "")).strip()]
# print(f"Built eval_set: {len(eval_set)} (question, note) pairs.")

# # === USE: run the eval (Anthropic cost per question) ===
# # Run all of them, or a slice like eval_set[0:10] to go in chunks.
# for i, (q_text, expected_s, expected_a) in enumerate(eval_set, start=1):
#     print(f"\n\n{'#'*80}")
#     print(f"# QUESTION {i}/{len(eval_set)}")
#     print(f"{'#'*80}")
#     run_eval_question(q_text, expected_a)

# import json
# output_path = '/content/drive/MyDrive/intl_arb_bot/evaluation_run.json'
# with open(output_path, 'w') as f:
#     json.dump(results, f, indent=2)
# print(f"Saved {len(results)} results to {output_path}")

# # === Build a grading spreadsheet from the saved eval results (NO tokens, NO API) ===
# # Run this in Colab after the results JSON is saved. Reads the file, writes an .xlsx
# # you grade by hand. Reruns are free — it only reads what you already have.

# import json
# from openpyxl import Workbook
# from openpyxl.styles import Font, Alignment, PatternFill
# from openpyxl.worksheet.datavalidation import DataValidation

# RESULTS_PATH = '/content/drive/MyDrive/intl_arb_bot/evaluation_run.json'
# OUT_PATH     = '/content/drive/MyDrive/intl_arb_bot/grading_sheet.xlsx'

# with open(RESULTS_PATH) as f:
#     results = json.load(f)

# def fmt_sources(retrieved):
#     """retrieved rows may be (id,title,score) tuples or dicts. Summarise as 'id  title'."""
#     out = []
#     for r in (retrieved or []):
#         if isinstance(r, dict):
#             cid = r.get('chunk_id', '?'); title = str(r.get('source_title', ''))[:40]
#         elif isinstance(r, (list, tuple)):
#             cid = r[0] if len(r) > 0 else '?'; title = str(r[1])[:40] if len(r) > 1 else ''
#         else:
#             cid, title = '?', str(r)[:40]
#         out.append(f"{cid}  {title}")
#     return "\n".join(out)

# wb = Workbook()
# ws = wb.active
# ws.title = "Grading"

# headers = ["#", "Question", "Expected behaviour", "Bot answer",
#            "Sources retrieved", "Grade", "Failure type", "Notes"]
# ws.append(headers)
# for c in ws[1]:
#     c.font = Font(bold=True, color="FFFFFF")
#     c.fill = PatternFill("solid", fgColor="374151")
#     c.alignment = Alignment(vertical="center")

# for i, r in enumerate(results, 1):
#     ws.append([
#         i,
#         r.get("question", ""),
#         r.get("expected", ""),
#         r.get("answer", ""),
#         fmt_sources(r.get("retrieved")),
#         "",   # Grade
#         "",   # Failure type
#         "",   # Notes
#     ])

# # dropdowns so grading is click-not-type
# grade_dv = DataValidation(type="list", formula1='"exceeded,met,fell short"', allow_blank=True)
# fail_dv  = DataValidation(type="list", formula1='"-,retrieval,generation,both"', allow_blank=True)
# ws.add_data_validation(grade_dv); ws.add_data_validation(fail_dv)
# last = len(results) + 1
# grade_dv.add(f"F2:F{last}"); fail_dv.add(f"G2:G{last}")

# widths = {"A":4, "B":40, "C":50, "D":80, "E":26, "F":12, "G":13, "H":30}
# for col, w in widths.items():
#     ws.column_dimensions[col].width = w
# for row in ws.iter_rows(min_row=2, max_row=last):
#     for cell in row:
#         cell.alignment = Alignment(wrap_text=True, vertical="top")

# # a summary sheet that auto-tallies as you fill grades
# s = wb.create_sheet("Summary")
# s["A1"] = "Grade";        s["B1"] = "Count"
# s["A2"] = "exceeded";     s["B2"] = f'=COUNTIF(Grading!F2:F{last},"exceeded")'
# s["A3"] = "met";          s["B3"] = f'=COUNTIF(Grading!F2:F{last},"met")'
# s["A4"] = "fell short";   s["B4"] = f'=COUNTIF(Grading!F2:F{last},"fell short")'
# s["A5"] = "met+exceeded"; s["B5"] = f'=B2+B3'
# s["A6"] = "TOTAL graded"; s["B6"] = f'=B2+B3+B4'
# s["A8"] = "Shortfalls by type"; s["A8"].font = Font(bold=True)
# s["A9"]  = "retrieval";  s["B9"]  = f'=COUNTIF(Grading!G2:G{last},"retrieval")'
# s["A10"] = "generation"; s["B10"] = f'=COUNTIF(Grading!G2:G{last},"generation")'
# s["A11"] = "both";       s["B11"] = f'=COUNTIF(Grading!G2:G{last},"both")'
# for r in range(1, 12):
#     s[f"A{r}"].font = Font(bold=(r in (1, 8)))
# s.column_dimensions["A"].width = 20; s.column_dimensions["B"].width = 40

# wb.save(OUT_PATH)
# print(f"Wrote grading sheet with {len(results)} rows to {OUT_PATH}")
# print("Grade column F (exceeded/met/fell short) and, for shortfalls, Failure type in G.")
# print("The Summary tab tallies automatically as you fill them in.")

"""# Section D - Diagnostics"""

SYSTEM_PROMPT